/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v15.0
processor: MCXA153
package_id: MCXA153VLH
mcu_data: ksdk2_0
processor_version: 15.0.0
pin_labels:
- {pin_num: '38', pin_signal: P3_12/LPUART2_RTS_B/CT1_MAT2/PWM0_X0, label: LED_RED, identifier: LED_RED}
- {pin_num: '37', pin_signal: P3_13/LPUART2_CTS_B/CT1_MAT3/PWM0_X1, label: LED_GREEN, identifier: LED_GREEN}
- {pin_num: '46', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/CT_INP16/PWM0_A0, label: PWM, identifier: LED_BLUE;PWM}
- {pin_num: '57', pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C0_SCL/CT_INP5/CT0_MAT3/ADC0_A17/CMP1_IN3, label: SCL, identifier: SCL}
- {pin_num: '56', pin_signal: P1_0/WUU0_IN6/LPTMR0_ALT3/TRIG_IN0/LPSPI0_SDO/LPI2C0_SDA/CT_INP4/CT0_MAT2/ADC0_A16/CMP0_IN3, label: INTERUPT_SENSOR, identifier: INTERUPT_SENSOR}
- {pin_num: '1', pin_signal: P1_7/WUU0_IN9/TRIG_OUT2/LPUART2_CTS_B/CT_INP7/ADC0_A23, label: SW_3, identifier: SW_3}
- {pin_num: '62', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/ADC0_A20/CMP0_IN2, label: UART_RX, identifier: INTERUPT_SENSOR;UART_RX;TASTER_L_T}
- {pin_num: '24', pin_signal: P2_16/LPSPI1_SDI/LPUART1_RTS_B/CT0_MAT2/ADC0_A6, label: TASTER_T_R, identifier: SPI_SDI;TASTER_T_R;a}
- {pin_num: '23', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT0_MAT1, label: TASTER_B_L, identifier: SPI_SDO;TASTER_B_L;B}
- {pin_num: '20', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/CT_INP18/CT1_MAT2/ADC0_A3, label: TASTER_T_L, identifier: SPI_CS;TASTER_T_L}
- {pin_num: '22', pin_signal: P2_12/WUU0_IN20/USB0_VBUS_DET/LPSPI1_SCK/LPUART1_RXD/CT0_MAT0/ADC0_A5, label: MOTOR_EN, identifier: SPI_CLK;TASTER_B_R;MOTOR_EN}
- {pin_num: '3', pin_signal: P1_9/LPUART1_TXD/LPI2C0_SCL/CT_INP9/CT0_MAT3/I3C0_SCL, label: I2C_SCL, identifier: I2C_SCL}
- {pin_num: '2', pin_signal: P1_8/WUU0_IN10/LPUART1_RXD/LPI2C0_SDA/CT_INP8/CT0_MAT2/I3C0_SDA, label: I2C_SDA, identifier: I2C_SDA}
- {pin_num: '63', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/ADC0_A21/CMP1_IN2, label: UART_TX, identifier: UART_TX}
- {pin_num: '44', pin_signal: P3_6/CLKOUT/LPSPI1_PCS3/PWM0_A0/FREQME_CLK_OUT1, label: PWM_ALL, identifier: PWM_white;PWM_ALL}
- {pin_num: '43', pin_signal: P3_7/TRIG_IN2/LPSPI1_PCS2/PWM0_B0, label: PWM_ALL, identifier: PWM_yellow;EN_WHITE;a;EN;NULL_TRIGGER;PWM_SERVO;PWM_ALL}
- {pin_num: '42', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/CLKOUT, label: NULL_TRIGGER, identifier: PWM_red;EN_YELLOW;NULL_TRIGGER}
- {pin_num: '41', pin_signal: P3_9/TRIG_IN4/LPSPI1_SDI/LPUART1_TXD/CT_INP5/PWM0_B1, label: SERVO_PWM, identifier: PWM_green;EN_RED;SERVO_PWM}
- {pin_num: '40', pin_signal: P3_10/TRIG_IN5/LPSPI1_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2, label: PWM, identifier: PWM_orange;EN_GREEN;SERVO_PWM;PWM}
- {pin_num: '39', pin_signal: P3_11/WUU0_IN24/TRIG_IN6/LPSPI1_PCS0/LPUART1_CTS_B/CT1_MAT1/PWM0_B2, label: EN_ORANGE, identifier: PWM_blue;EN_ORANGE}
- {pin_num: '30', pin_signal: P3_31/LPTMR0_ALT2/TRIG_IN10/CT0_MAT3/ADC0_A12, label: DIR_red, identifier: DIR_white;a;DIR_yellow;d;DIR_orange;g;r;DIR_red}
- {pin_num: '21', pin_signal: P2_7/TRIG_IN5/CT_INP19/CT1_MAT3/VREFI/ADC0_A7, label: MOTOR_ALL_EN, identifier: DIR_yellow;MOTOR_ALL_EN}
- {pin_num: '31', pin_signal: P3_30/TRIG_OUT6/CT0_MAT2/ADC0_A13, label: DIR_blue, identifier: DIR_red;DIR_white;a;DIR_blue}
- {pin_num: '14', pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/CT_INP16/CT2_MAT0/ADC0_A0, label: DIR_green, identifier: DIR;DIR_red;s;DIR_green;g}
- {pin_num: '7', pin_signal: P1_13/TRIG_IN3/LPUART2_TXD/CT2_MAT3/ADC0_A11, label: DIR_yellow, identifier: DIR_green;g;DIR_red;y;DIR_yellow}
- {pin_num: '6', pin_signal: P1_12/WUU0_IN12/LPUART2_RXD/CT2_MAT2/ADC0_A10, label: DIR_white, identifier: DIR_orange;k;DIR_yellow;w;DIR_white}
- {pin_num: '32', pin_signal: P3_29/WUU0_IN27/ISPMODE_N/CT_INP3/ADC0_A14, label: DIR_orange, identifier: DIR_blue;DIR_white;a;DIR_orange}
- {pin_num: '16', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/ADC0_A4/CMP0_IN0, label: TASTER_B_R, identifier: TASTER_CHECK;TASTER_T_R;TASTER__R;TASTER__B_R;TASTER_B_R}
- {pin_num: '15', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/CT_INP17/CT2_MAT1/ADC0_A1, label: LED_SWITCH, identifier: LED_SWITCH}
- {pin_num: '5', pin_signal: P1_11/WUU0_IN11/TRIG_OUT2/LPUART1_CTS_B/LPI2C0_SCLS/CT2_MAT1/I3C0_PUR/ADC0_A9, label: DIR_orange, identifier: ALL_MOTOR_EN;DIR_orange}
- {pin_num: '64', pin_signal: P1_6/TRIG_IN2/LPSPI0_PCS1/LPUART2_RTS_B/CT_INP6/ADC0_A22, label: INTERUPT_SENSOR, identifier: INTERUPT_SENSOR}
- {pin_num: '45', pin_signal: P3_1/TRIG_IN1/CT_INP17/PWM0_B0/FREQME_CLK_OUT0, label: EN_GREEN, identifier: EN_BLUE;a;EN_;EN_GREEN}
- {pin_num: '19', pin_signal: P2_5/CT_INP15/CT1_MAT1, label: EN_RED, identifier: EN_ORANGE;b;EN_RED}
- {pin_num: '18', pin_signal: P2_4/CT_INP14/CT1_MAT0, label: EN_YELLOW, identifier: EN_GREEN;a;EN_YELLOW}
- {pin_num: '17', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/ADC0_A2/CMP1_IN0, label: EN_WHITE, identifier: EN_RED;EN_WHITE}
- {pin_num: '36', pin_signal: P3_14/WUU0_IN25/LPUART2_RXD/CT_INP6/PWM0_X2, label: EN_BLUE, identifier: EN_BLUE}
- {pin_num: '35', pin_signal: P3_15/LPUART2_TXD/CT_INP7, label: EN_ORANGE, identifier: EN_ORANGE}
- {pin_num: '4', pin_signal: P1_10/LPUART1_RTS_B/LPI2C0_SDAS/CT2_MAT0/ADC0_A8, label: DIR_TEST, identifier: DIR_TEST}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitCOM();
    BOARD_InitLED();
    BOARD_InitSW();
    BOARD_InitCLOCK();
    BOARD_InitPWM();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCOM:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '62', peripheral: LPUART2, signal: RX, pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/ADC0_A20/CMP0_IN2, identifier: UART_RX}
  - {pin_num: '63', peripheral: LPUART2, signal: TX, pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/ADC0_A21/CMP1_IN2}
  - {pin_num: '3', peripheral: LPI2C0, signal: SCL, pin_signal: P1_9/LPUART1_TXD/LPI2C0_SCL/CT_INP9/CT0_MAT3/I3C0_SCL, pull_select: up, pull_enable: enable}
  - {pin_num: '2', peripheral: LPI2C0, signal: SDA, pin_signal: P1_8/WUU0_IN10/LPUART1_RXD/LPI2C0_SDA/CT_INP8/CT0_MAT2/I3C0_SDA, pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCOM
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCOM(void)
{
    /* Write to PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* LPUART2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART2_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* LPI2C0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPI2C0_RST_SHIFT_RSTn);

    /* PORT1_4 (pin 62) is configured as LPUART2_RXD */
    PORT_SetPinMux(BOARD_INITCOM_UART_RX_PORT, BOARD_INITCOM_UART_RX_PIN, kPORT_MuxAlt3);

    PORT1->PCR[4] = ((PORT1->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_5 (pin 63) is configured as LPUART2_TXD */
    PORT_SetPinMux(BOARD_INITCOM_UART_TX_PORT, BOARD_INITCOM_UART_TX_PIN, kPORT_MuxAlt3);

    PORT1->PCR[5] = ((PORT1->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_8 (pin 2) is configured as LPI2C0_SDA */
    PORT_SetPinMux(BOARD_INITCOM_I2C_SDA_PORT, BOARD_INITCOM_I2C_SDA_PIN, kPORT_MuxAlt3);

    PORT1->PCR[8] = ((PORT1->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_IBE_MASK)))

                     /* Pull Select: Enables internal pullup resistor. */
                     | PORT_PCR_PS(PCR_PS_ps1)

                     /* Pull Enable: Enables. */
                     | PORT_PCR_PE(PCR_PE_pe1)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_9 (pin 3) is configured as LPI2C0_SCL */
    PORT_SetPinMux(BOARD_INITCOM_I2C_SCL_PORT, BOARD_INITCOM_I2C_SCL_PIN, kPORT_MuxAlt3);

    PORT1->PCR[9] = ((PORT1->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_IBE_MASK)))

                     /* Pull Select: Enables internal pullup resistor. */
                     | PORT_PCR_PS(PCR_PS_ps1)

                     /* Pull Enable: Enables. */
                     | PORT_PCR_PE(PCR_PE_pe1)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLED:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true', fullInit: 'true'}
- pin_list:
  - {pin_num: '38', peripheral: GPIO3, signal: 'GPIO, 12', pin_signal: P3_12/LPUART2_RTS_B/CT1_MAT2/PWM0_X0, direction: OUTPUT, gpio_init_state: 'false', slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '37', peripheral: GPIO3, signal: 'GPIO, 13', pin_signal: P3_13/LPUART2_CTS_B/CT1_MAT3/PWM0_X1, direction: OUTPUT, gpio_init_state: 'false', slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '46', peripheral: GPIO3, signal: 'GPIO, 0', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/CT_INP16/PWM0_A0, identifier: LED_BLUE, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, extra_drive_strength: normal, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable,
    invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLED
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLED(void)
{
    /* Write to GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* Write to PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    gpio_pin_config_t LED_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_0 (pin 46)  */
    GPIO_PinInit(BOARD_INITLED_LED_BLUE_GPIO, BOARD_INITLED_LED_BLUE_PIN, &LED_BLUE_config);

    gpio_pin_config_t LED_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_12 (pin 38)  */
    GPIO_PinInit(BOARD_INITLED_LED_RED_GPIO, BOARD_INITLED_LED_RED_PIN, &LED_RED_config);

    gpio_pin_config_t LED_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_13 (pin 37)  */
    GPIO_PinInit(BOARD_INITLED_LED_GREEN_GPIO, BOARD_INITLED_LED_GREEN_PIN, &LED_GREEN_config);

    const port_pin_config_t LED_BLUE = {/* Internal pull-up/down resistor is disabled */
                                        kPORT_PullDisable,
                                        /* Low internal pull resistor value is selected. */
                                        kPORT_LowPullResistor,
                                        /* Fast slew rate is configured */
                                        kPORT_FastSlewRate,
                                        /* Passive input filter is disabled */
                                        kPORT_PassiveFilterDisable,
                                        /* Open drain output is disabled */
                                        kPORT_OpenDrainDisable,
                                        /* Low drive strength is configured */
                                        kPORT_LowDriveStrength,
                                        /* Normal drive strength is configured */
                                        kPORT_NormalDriveStrength,
                                        /* Pin is configured as P3_0 */
                                        kPORT_MuxAlt0,
                                        /* Digital input enabled */
                                        kPORT_InputBufferEnable,
                                        /* Digital input is not inverted */
                                        kPORT_InputNormal,
                                        /* Pin Control Register fields [15:0] are not locked */
                                        kPORT_UnlockRegister};
    /* PORT3_0 (pin 46) is configured as P3_0 */
    PORT_SetPinConfig(BOARD_INITLED_LED_BLUE_PORT, BOARD_INITLED_LED_BLUE_PIN, &LED_BLUE);

    const port_pin_config_t LED_RED = {/* Internal pull-up/down resistor is disabled */
                                       kPORT_PullDisable,
                                       /* Low internal pull resistor value is selected. */
                                       kPORT_LowPullResistor,
                                       /* Fast slew rate is configured */
                                       kPORT_FastSlewRate,
                                       /* Passive input filter is disabled */
                                       kPORT_PassiveFilterDisable,
                                       /* Open drain output is disabled */
                                       kPORT_OpenDrainDisable,
                                       /* Low drive strength is configured */
                                       kPORT_LowDriveStrength,
                                       /* Normal drive strength is configured */
                                       kPORT_NormalDriveStrength,
                                       /* Pin is configured as P3_12 */
                                       kPORT_MuxAlt0,
                                       /* Digital input enabled */
                                       kPORT_InputBufferEnable,
                                       /* Digital input is not inverted */
                                       kPORT_InputNormal,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       kPORT_UnlockRegister};
    /* PORT3_12 (pin 38) is configured as P3_12 */
    PORT_SetPinConfig(BOARD_INITLED_LED_RED_PORT, BOARD_INITLED_LED_RED_PIN, &LED_RED);

    const port_pin_config_t LED_GREEN = {/* Internal pull-up/down resistor is disabled */
                                         kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as P3_13 */
                                         kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT3_13 (pin 37) is configured as P3_13 */
    PORT_SetPinConfig(BOARD_INITLED_LED_GREEN_PORT, BOARD_INITLED_LED_GREEN_PIN, &LED_GREEN);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSW:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: GPIO1, signal: 'GPIO, 7', pin_signal: P1_7/WUU0_IN9/TRIG_OUT2/LPUART2_CTS_B/CT_INP7/ADC0_A23, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptFallingEdge}
  - {pin_num: '20', peripheral: GPIO2, signal: 'GPIO, 6', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/CT_INP18/CT1_MAT2/ADC0_A3, identifier: TASTER_T_L, direction: INPUT,
    gpio_per_interrupt: kGPIO_InterruptFallingEdge, pull_select: up, pull_enable: enable}
  - {pin_num: '23', peripheral: GPIO2, signal: 'GPIO, 13', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT0_MAT1, identifier: TASTER_B_L, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptFallingEdge,
    pull_select: up, pull_enable: enable}
  - {pin_num: '16', peripheral: GPIO2, signal: 'GPIO, 2', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/ADC0_A4/CMP0_IN0, identifier: TASTER_B_R,
    direction: INPUT, gpio_per_interrupt: kGPIO_InterruptFallingEdge, pull_select: up, pull_enable: enable}
  - {pin_num: '24', peripheral: GPIO2, signal: 'GPIO, 16', pin_signal: P2_16/LPSPI1_SDI/LPUART1_RTS_B/CT0_MAT2/ADC0_A6, identifier: TASTER_T_R, direction: INPUT,
    gpio_per_interrupt: kGPIO_InterruptFallingEdge, pull_select: up, pull_enable: enable}
  - {pin_num: '15', peripheral: GPIO2, signal: 'GPIO, 1', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/CT_INP17/CT2_MAT1/ADC0_A1, direction: OUTPUT}
  - {pin_num: '64', peripheral: GPIO1, signal: 'GPIO, 6', pin_signal: P1_6/TRIG_IN2/LPSPI0_PCS1/LPUART2_RTS_B/CT_INP6/ADC0_A22, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptFallingEdge,
    pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSW
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSW(void)
{
    /* Write to GPIO1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO1);
    /* Write to GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* Write to PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* Write to PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* GPIO1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    gpio_pin_config_t INTERUPT_SENSOR_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_6 (pin 64)  */
    GPIO_PinInit(BOARD_INITSW_INTERUPT_SENSOR_GPIO, BOARD_INITSW_INTERUPT_SENSOR_PIN, &INTERUPT_SENSOR_config);

    gpio_pin_config_t SW_3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_7 (pin 1)  */
    GPIO_PinInit(BOARD_INITSW_SW_3_GPIO, BOARD_INITSW_SW_3_PIN, &SW_3_config);

    gpio_pin_config_t LED_SWITCH_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_1 (pin 15)  */
    GPIO_PinInit(BOARD_INITSW_LED_SWITCH_GPIO, BOARD_INITSW_LED_SWITCH_PIN, &LED_SWITCH_config);

    gpio_pin_config_t TASTER_B_R_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_2 (pin 16)  */
    GPIO_PinInit(BOARD_INITSW_TASTER_B_R_GPIO, BOARD_INITSW_TASTER_B_R_PIN, &TASTER_B_R_config);

    gpio_pin_config_t TASTER_T_L_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_6 (pin 20)  */
    GPIO_PinInit(BOARD_INITSW_TASTER_T_L_GPIO, BOARD_INITSW_TASTER_T_L_PIN, &TASTER_T_L_config);

    gpio_pin_config_t TASTER_B_L_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_13 (pin 23)  */
    GPIO_PinInit(BOARD_INITSW_TASTER_B_L_GPIO, BOARD_INITSW_TASTER_B_L_PIN, &TASTER_B_L_config);

    gpio_pin_config_t TASTER_T_R_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_16 (pin 24)  */
    GPIO_PinInit(BOARD_INITSW_TASTER_T_R_GPIO, BOARD_INITSW_TASTER_T_R_PIN, &TASTER_T_R_config);

    /* Interrupt configuration on GPIO1_6 (pin 64): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITSW_INTERUPT_SENSOR_GPIO, BOARD_INITSW_INTERUPT_SENSOR_PIN, kGPIO_InterruptFallingEdge);

    /* Interrupt configuration on GPIO1_7 (pin 1): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITSW_SW_3_GPIO, BOARD_INITSW_SW_3_PIN, kGPIO_InterruptFallingEdge);

    /* Interrupt configuration on GPIO2_13 (pin 23): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITSW_TASTER_B_L_GPIO, BOARD_INITSW_TASTER_B_L_PIN, kGPIO_InterruptFallingEdge);

    /* Interrupt configuration on GPIO2_16 (pin 24): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITSW_TASTER_T_R_GPIO, BOARD_INITSW_TASTER_T_R_PIN, kGPIO_InterruptFallingEdge);

    /* Interrupt configuration on GPIO2_2 (pin 16): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITSW_TASTER_B_R_GPIO, BOARD_INITSW_TASTER_B_R_PIN, kGPIO_InterruptFallingEdge);

    /* Interrupt configuration on GPIO2_6 (pin 20): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITSW_TASTER_T_L_GPIO, BOARD_INITSW_TASTER_T_L_PIN, kGPIO_InterruptFallingEdge);

    /* PORT1_6 (pin 64) is configured as P1_6 */
    PORT_SetPinMux(BOARD_INITSW_INTERUPT_SENSOR_PORT, BOARD_INITSW_INTERUPT_SENSOR_PIN, kPORT_MuxAlt0);

    PORT1->PCR[6] = ((PORT1->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_IBE_MASK)))

                     /* Pull Select: Enables internal pullup resistor. */
                     | PORT_PCR_PS(PCR_PS_ps1)

                     /* Pull Enable: Enables. */
                     | PORT_PCR_PE(PCR_PE_pe1)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_7 (pin 1) is configured as P1_7 */
    PORT_SetPinMux(BOARD_INITSW_SW_3_PORT, BOARD_INITSW_SW_3_PIN, kPORT_MuxAlt0);

    PORT1->PCR[7] = ((PORT1->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[1] = ((PORT2->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_1 (pin 15) is configured as P2_1. */
                     | PORT_PCR_MUX(PORT2_PCR1_MUX_mux00)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[13] = ((PORT2->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pull Select: Enables internal pullup resistor. */
                      | PORT_PCR_PS(PCR_PS_ps1)

                      /* Pull Enable: Enables. */
                      | PORT_PCR_PE(PCR_PE_pe1)

                      /* Pin Multiplex Control: PORT2_13 (pin 23) is configured as P2_13. */
                      | PORT_PCR_MUX(PORT2_PCR13_MUX_mux00)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[16] = ((PORT2->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pull Select: Enables internal pullup resistor. */
                      | PORT_PCR_PS(PCR_PS_ps1)

                      /* Pull Enable: Enables. */
                      | PORT_PCR_PE(PCR_PE_pe1)

                      /* Pin Multiplex Control: PORT2_16 (pin 24) is configured as P2_16. */
                      | PORT_PCR_MUX(PORT2_PCR16_MUX_mux00)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[2] = ((PORT2->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pull Select: Enables internal pullup resistor. */
                     | PORT_PCR_PS(PCR_PS_ps1)

                     /* Pull Enable: Enables. */
                     | PORT_PCR_PE(PCR_PE_pe1)

                     /* Pin Multiplex Control: PORT2_2 (pin 16) is configured as P2_2. */
                     | PORT_PCR_MUX(PORT2_PCR2_MUX_mux00)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[6] = ((PORT2->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pull Select: Enables internal pullup resistor. */
                     | PORT_PCR_PS(PCR_PS_ps1)

                     /* Pull Enable: Enables. */
                     | PORT_PCR_PE(PCR_PE_pe1)

                     /* Pin Multiplex Control: PORT2_6 (pin 20) is configured as P2_6. */
                     | PORT_PCR_MUX(PORT2_PCR6_MUX_mux00)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCLOCK:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCLOCK
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCLOCK(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPWM:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true', fullInit: 'true'}
- pin_list:
  - {pin_num: '31', peripheral: GPIO3, signal: 'GPIO, 30', pin_signal: P3_30/TRIG_OUT6/CT0_MAT2/ADC0_A13, identifier: DIR_blue, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '14', peripheral: GPIO2, signal: 'GPIO, 0', pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/CT_INP16/CT2_MAT0/ADC0_A0, identifier: DIR_green, direction: OUTPUT,
    gpio_init_state: 'false', slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '7', peripheral: GPIO1, signal: 'GPIO, 13', pin_signal: P1_13/TRIG_IN3/LPUART2_TXD/CT2_MAT3/ADC0_A11, identifier: DIR_yellow, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '6', peripheral: GPIO1, signal: 'GPIO, 12', pin_signal: P1_12/WUU0_IN12/LPUART2_RXD/CT2_MAT2/ADC0_A10, identifier: DIR_white, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '45', peripheral: GPIO3, signal: 'GPIO, 1', pin_signal: P3_1/TRIG_IN1/CT_INP17/PWM0_B0/FREQME_CLK_OUT0, identifier: EN_GREEN, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, extra_drive_strength: normal, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable,
    invert_input: normal}
  - {pin_num: '19', peripheral: GPIO2, signal: 'GPIO, 5', pin_signal: P2_5/CT_INP15/CT1_MAT1, identifier: EN_RED, direction: OUTPUT, gpio_init_state: 'false', slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '18', peripheral: GPIO2, signal: 'GPIO, 4', pin_signal: P2_4/CT_INP14/CT1_MAT0, identifier: EN_YELLOW, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '36', peripheral: GPIO3, signal: 'GPIO, 14', pin_signal: P3_14/WUU0_IN25/LPUART2_RXD/CT_INP6/PWM0_X2, direction: OUTPUT, gpio_init_state: 'false', slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '35', peripheral: GPIO3, signal: 'GPIO, 15', pin_signal: P3_15/LPUART2_TXD/CT_INP7, direction: OUTPUT, gpio_init_state: 'false', slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '17', peripheral: GPIO2, signal: 'GPIO, 3', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/ADC0_A2/CMP1_IN0, identifier: EN_WHITE,
    direction: OUTPUT, gpio_init_state: 'false', slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable,
    invert_input: normal}
  - {pin_num: '42', peripheral: GPIO3, signal: 'GPIO, 8', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/CLKOUT, identifier: NULL_TRIGGER,
    direction: INPUT, gpio_per_interrupt: kGPIO_InterruptFallingEdge, slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: up, pull_enable: enable,
    input_buffer: enable, invert_input: normal}
  - {pin_num: '32', peripheral: GPIO3, signal: 'GPIO, 29', pin_signal: P3_29/WUU0_IN27/ISPMODE_N/CT_INP3/ADC0_A14, identifier: DIR_orange, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '30', peripheral: GPIO3, signal: 'GPIO, 31', pin_signal: P3_31/LPTMR0_ALT2/TRIG_IN10/CT0_MAT3/ADC0_A12, identifier: DIR_red, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '41', peripheral: FlexPWM0, signal: 'B, 1', pin_signal: P3_9/TRIG_IN4/LPSPI1_SDI/LPUART1_TXD/CT_INP5/PWM0_B1, identifier: SERVO_PWM, slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '44', peripheral: FlexPWM0, signal: 'A, 0', pin_signal: P3_6/CLKOUT/LPSPI1_PCS3/PWM0_A0/FREQME_CLK_OUT1, identifier: PWM_ALL, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '21', peripheral: GPIO2, signal: 'GPIO, 7', pin_signal: P2_7/TRIG_IN5/CT_INP19/CT1_MAT3/VREFI/ADC0_A7, identifier: MOTOR_ALL_EN, direction: OUTPUT,
    gpio_init_state: 'false', slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPWM
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPWM(void)
{
    /* Write to GPIO1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO1);
    /* Write to GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* Write to GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* Write to PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* Write to PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* Write to PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    /* FLEXPWM0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXPWM0_RST_SHIFT_RSTn);

    gpio_pin_config_t DIR_white_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_12 (pin 6)  */
    GPIO_PinInit(BOARD_INITPWM_DIR_white_GPIO, BOARD_INITPWM_DIR_white_PIN, &DIR_white_config);

    gpio_pin_config_t DIR_yellow_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_13 (pin 7)  */
    GPIO_PinInit(BOARD_INITPWM_DIR_yellow_GPIO, BOARD_INITPWM_DIR_yellow_PIN, &DIR_yellow_config);

    gpio_pin_config_t DIR_green_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_0 (pin 14)  */
    GPIO_PinInit(BOARD_INITPWM_DIR_green_GPIO, BOARD_INITPWM_DIR_green_PIN, &DIR_green_config);

    gpio_pin_config_t EN_WHITE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_3 (pin 17)  */
    GPIO_PinInit(BOARD_INITPWM_EN_WHITE_GPIO, BOARD_INITPWM_EN_WHITE_PIN, &EN_WHITE_config);

    gpio_pin_config_t EN_YELLOW_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_4 (pin 18)  */
    GPIO_PinInit(BOARD_INITPWM_EN_YELLOW_GPIO, BOARD_INITPWM_EN_YELLOW_PIN, &EN_YELLOW_config);

    gpio_pin_config_t EN_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_5 (pin 19)  */
    GPIO_PinInit(BOARD_INITPWM_EN_RED_GPIO, BOARD_INITPWM_EN_RED_PIN, &EN_RED_config);

    gpio_pin_config_t MOTOR_ALL_EN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_7 (pin 21)  */
    GPIO_PinInit(BOARD_INITPWM_MOTOR_ALL_EN_GPIO, BOARD_INITPWM_MOTOR_ALL_EN_PIN, &MOTOR_ALL_EN_config);

    gpio_pin_config_t EN_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_1 (pin 45)  */
    GPIO_PinInit(BOARD_INITPWM_EN_GREEN_GPIO, BOARD_INITPWM_EN_GREEN_PIN, &EN_GREEN_config);

    gpio_pin_config_t NULL_TRIGGER_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_8 (pin 42)  */
    GPIO_PinInit(BOARD_INITPWM_NULL_TRIGGER_GPIO, BOARD_INITPWM_NULL_TRIGGER_PIN, &NULL_TRIGGER_config);

    gpio_pin_config_t EN_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_14 (pin 36)  */
    GPIO_PinInit(BOARD_INITPWM_EN_BLUE_GPIO, BOARD_INITPWM_EN_BLUE_PIN, &EN_BLUE_config);

    gpio_pin_config_t EN_ORANGE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_15 (pin 35)  */
    GPIO_PinInit(BOARD_INITPWM_EN_ORANGE_GPIO, BOARD_INITPWM_EN_ORANGE_PIN, &EN_ORANGE_config);

    gpio_pin_config_t DIR_orange_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_29 (pin 32)  */
    GPIO_PinInit(BOARD_INITPWM_DIR_orange_GPIO, BOARD_INITPWM_DIR_orange_PIN, &DIR_orange_config);

    gpio_pin_config_t DIR_blue_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_30 (pin 31)  */
    GPIO_PinInit(BOARD_INITPWM_DIR_blue_GPIO, BOARD_INITPWM_DIR_blue_PIN, &DIR_blue_config);

    gpio_pin_config_t DIR_red_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_31 (pin 30)  */
    GPIO_PinInit(BOARD_INITPWM_DIR_red_GPIO, BOARD_INITPWM_DIR_red_PIN, &DIR_red_config);

    /* Interrupt configuration on GPIO3_8 (pin 42): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITPWM_NULL_TRIGGER_GPIO, BOARD_INITPWM_NULL_TRIGGER_PIN, kGPIO_InterruptFallingEdge);

    const port_pin_config_t DIR_white = {/* Internal pull-up/down resistor is disabled */
                                         kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as P1_12 */
                                         kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT1_12 (pin 6) is configured as P1_12 */
    PORT_SetPinConfig(BOARD_INITPWM_DIR_white_PORT, BOARD_INITPWM_DIR_white_PIN, &DIR_white);

    const port_pin_config_t DIR_yellow = {/* Internal pull-up/down resistor is disabled */
                                          kPORT_PullDisable,
                                          /* Low internal pull resistor value is selected. */
                                          kPORT_LowPullResistor,
                                          /* Fast slew rate is configured */
                                          kPORT_FastSlewRate,
                                          /* Passive input filter is disabled */
                                          kPORT_PassiveFilterDisable,
                                          /* Open drain output is disabled */
                                          kPORT_OpenDrainDisable,
                                          /* Low drive strength is configured */
                                          kPORT_LowDriveStrength,
                                          /* Normal drive strength is configured */
                                          kPORT_NormalDriveStrength,
                                          /* Pin is configured as P1_13 */
                                          kPORT_MuxAlt0,
                                          /* Digital input enabled */
                                          kPORT_InputBufferEnable,
                                          /* Digital input is not inverted */
                                          kPORT_InputNormal,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          kPORT_UnlockRegister};
    /* PORT1_13 (pin 7) is configured as P1_13 */
    PORT_SetPinConfig(BOARD_INITPWM_DIR_yellow_PORT, BOARD_INITPWM_DIR_yellow_PIN, &DIR_yellow);

    const port_pin_config_t DIR_green = {/* Internal pull-up/down resistor is disabled */
                                         kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as P2_0 */
                                         kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT2_0 (pin 14) is configured as P2_0 */
    PORT_SetPinConfig(BOARD_INITPWM_DIR_green_PORT, BOARD_INITPWM_DIR_green_PIN, &DIR_green);

    const port_pin_config_t EN_WHITE = {/* Internal pull-up/down resistor is disabled */
                                        kPORT_PullDisable,
                                        /* Low internal pull resistor value is selected. */
                                        kPORT_LowPullResistor,
                                        /* Fast slew rate is configured */
                                        kPORT_FastSlewRate,
                                        /* Passive input filter is disabled */
                                        kPORT_PassiveFilterDisable,
                                        /* Open drain output is disabled */
                                        kPORT_OpenDrainDisable,
                                        /* Low drive strength is configured */
                                        kPORT_LowDriveStrength,
                                        /* Normal drive strength is configured */
                                        kPORT_NormalDriveStrength,
                                        /* Pin is configured as P2_3 */
                                        kPORT_MuxAlt0,
                                        /* Digital input enabled */
                                        kPORT_InputBufferEnable,
                                        /* Digital input is not inverted */
                                        kPORT_InputNormal,
                                        /* Pin Control Register fields [15:0] are not locked */
                                        kPORT_UnlockRegister};
    /* PORT2_3 (pin 17) is configured as P2_3 */
    PORT_SetPinConfig(BOARD_INITPWM_EN_WHITE_PORT, BOARD_INITPWM_EN_WHITE_PIN, &EN_WHITE);

    const port_pin_config_t EN_YELLOW = {/* Internal pull-up/down resistor is disabled */
                                         kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as P2_4 */
                                         kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT2_4 (pin 18) is configured as P2_4 */
    PORT_SetPinConfig(BOARD_INITPWM_EN_YELLOW_PORT, BOARD_INITPWM_EN_YELLOW_PIN, &EN_YELLOW);

    const port_pin_config_t EN_RED = {/* Internal pull-up/down resistor is disabled */
                                      kPORT_PullDisable,
                                      /* Low internal pull resistor value is selected. */
                                      kPORT_LowPullResistor,
                                      /* Fast slew rate is configured */
                                      kPORT_FastSlewRate,
                                      /* Passive input filter is disabled */
                                      kPORT_PassiveFilterDisable,
                                      /* Open drain output is disabled */
                                      kPORT_OpenDrainDisable,
                                      /* Low drive strength is configured */
                                      kPORT_LowDriveStrength,
                                      /* Normal drive strength is configured */
                                      kPORT_NormalDriveStrength,
                                      /* Pin is configured as P2_5 */
                                      kPORT_MuxAlt0,
                                      /* Digital input enabled */
                                      kPORT_InputBufferEnable,
                                      /* Digital input is not inverted */
                                      kPORT_InputNormal,
                                      /* Pin Control Register fields [15:0] are not locked */
                                      kPORT_UnlockRegister};
    /* PORT2_5 (pin 19) is configured as P2_5 */
    PORT_SetPinConfig(BOARD_INITPWM_EN_RED_PORT, BOARD_INITPWM_EN_RED_PIN, &EN_RED);

    const port_pin_config_t MOTOR_ALL_EN = {/* Internal pull-up/down resistor is disabled */
                                            kPORT_PullDisable,
                                            /* Low internal pull resistor value is selected. */
                                            kPORT_LowPullResistor,
                                            /* Fast slew rate is configured */
                                            kPORT_FastSlewRate,
                                            /* Passive input filter is disabled */
                                            kPORT_PassiveFilterDisable,
                                            /* Open drain output is disabled */
                                            kPORT_OpenDrainDisable,
                                            /* Low drive strength is configured */
                                            kPORT_LowDriveStrength,
                                            /* Normal drive strength is configured */
                                            kPORT_NormalDriveStrength,
                                            /* Pin is configured as P2_7 */
                                            kPORT_MuxAlt0,
                                            /* Digital input enabled */
                                            kPORT_InputBufferEnable,
                                            /* Digital input is not inverted */
                                            kPORT_InputNormal,
                                            /* Pin Control Register fields [15:0] are not locked */
                                            kPORT_UnlockRegister};
    /* PORT2_7 (pin 21) is configured as P2_7 */
    PORT_SetPinConfig(BOARD_INITPWM_MOTOR_ALL_EN_PORT, BOARD_INITPWM_MOTOR_ALL_EN_PIN, &MOTOR_ALL_EN);

    const port_pin_config_t EN_GREEN = {/* Internal pull-up/down resistor is disabled */
                                        kPORT_PullDisable,
                                        /* Low internal pull resistor value is selected. */
                                        kPORT_LowPullResistor,
                                        /* Fast slew rate is configured */
                                        kPORT_FastSlewRate,
                                        /* Passive input filter is disabled */
                                        kPORT_PassiveFilterDisable,
                                        /* Open drain output is disabled */
                                        kPORT_OpenDrainDisable,
                                        /* Low drive strength is configured */
                                        kPORT_LowDriveStrength,
                                        /* Normal drive strength is configured */
                                        kPORT_NormalDriveStrength,
                                        /* Pin is configured as P3_1 */
                                        kPORT_MuxAlt0,
                                        /* Digital input enabled */
                                        kPORT_InputBufferEnable,
                                        /* Digital input is not inverted */
                                        kPORT_InputNormal,
                                        /* Pin Control Register fields [15:0] are not locked */
                                        kPORT_UnlockRegister};
    /* PORT3_1 (pin 45) is configured as P3_1 */
    PORT_SetPinConfig(BOARD_INITPWM_EN_GREEN_PORT, BOARD_INITPWM_EN_GREEN_PIN, &EN_GREEN);

    const port_pin_config_t EN_BLUE = {/* Internal pull-up/down resistor is disabled */
                                       kPORT_PullDisable,
                                       /* Low internal pull resistor value is selected. */
                                       kPORT_LowPullResistor,
                                       /* Fast slew rate is configured */
                                       kPORT_FastSlewRate,
                                       /* Passive input filter is disabled */
                                       kPORT_PassiveFilterDisable,
                                       /* Open drain output is disabled */
                                       kPORT_OpenDrainDisable,
                                       /* Low drive strength is configured */
                                       kPORT_LowDriveStrength,
                                       /* Normal drive strength is configured */
                                       kPORT_NormalDriveStrength,
                                       /* Pin is configured as P3_14 */
                                       kPORT_MuxAlt0,
                                       /* Digital input enabled */
                                       kPORT_InputBufferEnable,
                                       /* Digital input is not inverted */
                                       kPORT_InputNormal,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       kPORT_UnlockRegister};
    /* PORT3_14 (pin 36) is configured as P3_14 */
    PORT_SetPinConfig(BOARD_INITPWM_EN_BLUE_PORT, BOARD_INITPWM_EN_BLUE_PIN, &EN_BLUE);

    const port_pin_config_t EN_ORANGE = {/* Internal pull-up/down resistor is disabled */
                                         kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as P3_15 */
                                         kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT3_15 (pin 35) is configured as P3_15 */
    PORT_SetPinConfig(BOARD_INITPWM_EN_ORANGE_PORT, BOARD_INITPWM_EN_ORANGE_PIN, &EN_ORANGE);

    const port_pin_config_t DIR_orange = {/* Internal pull-up/down resistor is disabled */
                                          kPORT_PullDisable,
                                          /* Low internal pull resistor value is selected. */
                                          kPORT_LowPullResistor,
                                          /* Fast slew rate is configured */
                                          kPORT_FastSlewRate,
                                          /* Passive input filter is disabled */
                                          kPORT_PassiveFilterDisable,
                                          /* Open drain output is disabled */
                                          kPORT_OpenDrainDisable,
                                          /* Low drive strength is configured */
                                          kPORT_LowDriveStrength,
                                          /* Normal drive strength is configured */
                                          kPORT_NormalDriveStrength,
                                          /* Pin is configured as P3_29 */
                                          kPORT_MuxAlt0,
                                          /* Digital input enabled */
                                          kPORT_InputBufferEnable,
                                          /* Digital input is not inverted */
                                          kPORT_InputNormal,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          kPORT_UnlockRegister};
    /* PORT3_29 (pin 32) is configured as P3_29 */
    PORT_SetPinConfig(BOARD_INITPWM_DIR_orange_PORT, BOARD_INITPWM_DIR_orange_PIN, &DIR_orange);

    const port_pin_config_t DIR_blue = {/* Internal pull-up/down resistor is disabled */
                                        kPORT_PullDisable,
                                        /* Low internal pull resistor value is selected. */
                                        kPORT_LowPullResistor,
                                        /* Fast slew rate is configured */
                                        kPORT_FastSlewRate,
                                        /* Passive input filter is disabled */
                                        kPORT_PassiveFilterDisable,
                                        /* Open drain output is disabled */
                                        kPORT_OpenDrainDisable,
                                        /* Low drive strength is configured */
                                        kPORT_LowDriveStrength,
                                        /* Normal drive strength is configured */
                                        kPORT_NormalDriveStrength,
                                        /* Pin is configured as P3_30 */
                                        kPORT_MuxAlt0,
                                        /* Digital input enabled */
                                        kPORT_InputBufferEnable,
                                        /* Digital input is not inverted */
                                        kPORT_InputNormal,
                                        /* Pin Control Register fields [15:0] are not locked */
                                        kPORT_UnlockRegister};
    /* PORT3_30 (pin 31) is configured as P3_30 */
    PORT_SetPinConfig(BOARD_INITPWM_DIR_blue_PORT, BOARD_INITPWM_DIR_blue_PIN, &DIR_blue);

    const port_pin_config_t DIR_red = {/* Internal pull-up/down resistor is disabled */
                                       kPORT_PullDisable,
                                       /* Low internal pull resistor value is selected. */
                                       kPORT_LowPullResistor,
                                       /* Fast slew rate is configured */
                                       kPORT_FastSlewRate,
                                       /* Passive input filter is disabled */
                                       kPORT_PassiveFilterDisable,
                                       /* Open drain output is disabled */
                                       kPORT_OpenDrainDisable,
                                       /* Low drive strength is configured */
                                       kPORT_LowDriveStrength,
                                       /* Normal drive strength is configured */
                                       kPORT_NormalDriveStrength,
                                       /* Pin is configured as P3_31 */
                                       kPORT_MuxAlt0,
                                       /* Digital input enabled */
                                       kPORT_InputBufferEnable,
                                       /* Digital input is not inverted */
                                       kPORT_InputNormal,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       kPORT_UnlockRegister};
    /* PORT3_31 (pin 30) is configured as P3_31 */
    PORT_SetPinConfig(BOARD_INITPWM_DIR_red_PORT, BOARD_INITPWM_DIR_red_PIN, &DIR_red);

    const port_pin_config_t PWM_ALL = {/* Internal pull-up/down resistor is disabled */
                                       kPORT_PullDisable,
                                       /* Low internal pull resistor value is selected. */
                                       kPORT_LowPullResistor,
                                       /* Fast slew rate is configured */
                                       kPORT_FastSlewRate,
                                       /* Passive input filter is disabled */
                                       kPORT_PassiveFilterDisable,
                                       /* Open drain output is disabled */
                                       kPORT_OpenDrainDisable,
                                       /* Low drive strength is configured */
                                       kPORT_LowDriveStrength,
                                       /* Normal drive strength is configured */
                                       kPORT_NormalDriveStrength,
                                       /* Pin is configured as PWM0_A0 */
                                       kPORT_MuxAlt5,
                                       /* Digital input enabled */
                                       kPORT_InputBufferEnable,
                                       /* Digital input is not inverted */
                                       kPORT_InputNormal,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       kPORT_UnlockRegister};
    /* PORT3_6 (pin 44) is configured as PWM0_A0 */
    PORT_SetPinConfig(BOARD_INITPWM_PWM_ALL_PORT, BOARD_INITPWM_PWM_ALL_PIN, &PWM_ALL);

    const port_pin_config_t NULL_TRIGGER = {/* Internal pull-up resistor is enabled */
                                            kPORT_PullUp,
                                            /* Low internal pull resistor value is selected. */
                                            kPORT_LowPullResistor,
                                            /* Fast slew rate is configured */
                                            kPORT_FastSlewRate,
                                            /* Passive input filter is disabled */
                                            kPORT_PassiveFilterDisable,
                                            /* Open drain output is disabled */
                                            kPORT_OpenDrainDisable,
                                            /* Low drive strength is configured */
                                            kPORT_LowDriveStrength,
                                            /* Normal drive strength is configured */
                                            kPORT_NormalDriveStrength,
                                            /* Pin is configured as P3_8 */
                                            kPORT_MuxAlt0,
                                            /* Digital input enabled */
                                            kPORT_InputBufferEnable,
                                            /* Digital input is not inverted */
                                            kPORT_InputNormal,
                                            /* Pin Control Register fields [15:0] are not locked */
                                            kPORT_UnlockRegister};
    /* PORT3_8 (pin 42) is configured as P3_8 */
    PORT_SetPinConfig(BOARD_INITPWM_NULL_TRIGGER_PORT, BOARD_INITPWM_NULL_TRIGGER_PIN, &NULL_TRIGGER);

    const port_pin_config_t SERVO_PWM = {/* Internal pull-up/down resistor is disabled */
                                         kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as PWM0_B1 */
                                         kPORT_MuxAlt5,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT3_9 (pin 41) is configured as PWM0_B1 */
    PORT_SetPinConfig(BOARD_INITPWM_SERVO_PWM_PORT, BOARD_INITPWM_SERVO_PWM_PIN, &SERVO_PWM);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
